heat_template_version: 2013-05-23

description: Simple template to deploy a single compute instance

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      key_name: akka-skomarov
      image: ubuntu-trusty
      flavor: m1.medium
      networks:
        - network: cloud
      user_data: |
        #!/bin/bash
        sudo chsh -s /bin/bash ec2-user
        echo "sudo apt-get update" >> /tmp/log
        sudo apt-get update
        echo "sudo apt-get install -y puppet git unzip" >> /tmp/log
        sudo apt-get install -y puppet git unzip
        echo "sudo cd /etc/puppet/modules" >> /tmp/log
        cd /etc/puppet/modules
        pwd >> /tmp/log
        echo "sudo puppet module install aco-oracle_java" >> /tmp/log
        sudo puppet module install aco-oracle_java
        echo "git clone https://github.com/tanSergo/tanRepo.git" >> /tmp/log
        git clone https://github.com/tanSergo/tanRepo.git
        echo "sudo cd /etc/puppet/modules/tanRepo" >> /tmp/log
        cd /etc/puppet/modules/tanRepo
        pwd >> /tmp/log
        echo "sudo mv /etc/puppet/modules/tanRepo/site.pp /etc/puppet/manifests/site.pp" >> /tmp/log
        sudo mv site.pp /etc/puppet/manifests/
        echo "puppet apply --modulepath /etc/puppet/modules/ /etc/puppet/manifests/site.pp" >> /tmp/log
        sudo puppet apply --modulepath /etc/puppet/modules/ /etc/puppet/manifests/site.pp >> /tmp/log
        echo "puppet apply complete!" >> /tmp/log
        echo "sudo source /home/ec2-user/.profile" >> /tmp/log
        sudo source /home/ec2-user/.profile
        echo "cd /etc/puppet/modules/tanRepo" >> /tmp/log
        cd /etc/puppet/modules/tanRepo
        echo "sudo unzip testproject1.zip" >> /tmp/log
        sudo unzip testproject1.zip
        echo "sudo mv /etc/puppet/modules/tanRepo/.profile /home/ec2-user/.profile" >> /tmp/log
        sudo mv /etc/puppet/modules/tanRepo/.profile /home/ec2-user/.profile
        echo "cd /etc/puppet/modules/tanRepo/testproject1" >> /tmp/log
        cd /etc/puppet/modules/tanRepo/testproject1
        echo "java -jar target/lab_0-1.0-SNAPSHOT-shaded.jar" >> /tmp/log
        java -jar target/lab_0-1.0-SNAPSHOT-shaded.jar >> /tmp/akka &
